taproot address validation
photon-sdk/photon-lib pull request #30
Opened 2021-12-28 02:21 UTC by xsats

Add validation logic for taproot/unknown segwit versions. Thanks to bitcoinjs/BlueWallet

2021-12-28 02:30 UTC, xsats commented
AFAIK this should also add support for sending to bech32m addresses through the upgrate to `bitcoinjs-lib` v^6.0.0.

2022-01-26 03:42 UTC, BitcoinZavior commented
@xsats can you provide the .env file you used to run the test cases. I can test your branch add add the results here.

2022-01-29 20:21 UTC, xsats commented
Hey @BitcoinZavior! Unfortunately I don't have access to the original .env file either so I'm unable to share the missing mnemonics. 

@tanx - are you able to share this? Test scripts work for the specific changes introduced by my two PRs, which use the hardcoded mnemonics but obviously would be great to validate the entire suite without rewriting the results.

2022-01-30 15:52 UTC, tanx commented
> @tanx - are you able to share this? Test scripts work for the specific changes introduced by my two PRs, which use the hardcoded mnemonics but obviously would be great to validate the entire suite without rewriting the results.

See https://github.com/photon-sdk/photon-lib/issues/33#issuecomment-1025169480

2022-01-31 11:02 UTC, xsats commented
@tanx what are your plans for Photon going forwards? Do you need help with review of PRs/maintaining the repo?

2022-01-31 15:20 UTC, tanx commented
> @tanx what are your plans for Photon going forwards? Do you need help with review of PRs/maintaining the repo?

Yes, I'm happy to hand over maintenance of the project if someone steps up to take ownership of reviewing PRs, etc.

2022-01-31 15:25 UTC, tanx commented
Also, I'm happy to do a handover/transition and offer some mentorship during this period.

2022-02-01 17:13 UTC, xsats commented
Great - more than happy to help maintain the project and very grateful for any of your guidance during the transition. @BitcoinZavior also expressed interest on this so happy to work with you both

2022-04-18 11:46 UTC, tanx requested changes
LGTM ... just a minor nit

2022-04-18 11:46 UTC, tanx commented on src/wallet/multisig-hd-wallet.js
> +
```suggestion
```

2022-04-18 11:47 UTC, tanx commented
> LGTM ... just a minor nit

Ah wait sorry, just looked at the last commit. Will take another look for the rest.

2022-04-18 11:55 UTC, tanx commented
I gave the whole PR another review. Generally looks good. The tests are failing... likely since it's based on an outdated master. Can you rebase to the current master and then we can see if tests pass? Thanks 🙏

2022-09-21 22:11 UTC, closed without merging